### PR TITLE
Add zh_cn.json

### PR DESCRIPTION
**Pull request by Nana-Sakura**
The language file is translated into Chinese by @Devanaoi.

### CODE REVIEW

**Comment by Kasualix** [comment]
文件里的半角字符应该改成全角（包括但不限于[这里](https://github.com/wxkj123/MCDoom/blob/70f4d5550089f3b6d7ed9e670967ca5fea85a127/src/main/resources/assets/doom/lang/zh_cn.json#L49)、[这里](https://github.com/wxkj123/MCDoom/blob/70f4d5550089f3b6d7ed9e670967ca5fea85a127/src/main/resources/assets/doom/lang/zh_cn.json#L219)和[这里](https://github.com/wxkj123/MCDoom/blob/70f4d5550089f3b6d7ed9e670967ca5fea85a127/src/main/resources/assets/doom/lang/zh_cn.json#L341)）。

**Comment by AzureDoom** [comment]
They can not be changed as they are in-code name of the mod and changing it will remove the old items from saves.

**Comment by Kasualix** [comment]
> They can not be changed as they are in-code name of the mod and changing it will remove the old items from saves.

Oh, the keys don't need to be changed.
I mean the half-width characters in Chinese translation. 
[here](https://github.com/wxkj123/MCDoom/blob/70f4d5550089f3b6d7ed9e670967ca5fea85a127/src/main/resources/assets/doom/lang/zh_cn.json#L49)"item.doom.cruciblesword_closed":"裁决剑(失效)" should be "item.doom.cruciblesword_closed":"裁决剑（失效）"
"(" → "（"
")" → "）"

**Comment by AzureDoom** [comment]
Ahhh, yeah, was waiting to hear a back from a buddy to vet the file to be safe 😅 that's why it wasn't merged yet

**Comment by Nana-Sakura** [comment]
> > They can not be changed as they are in-code name of the mod and changing it will remove the old items from saves.
> 
> Oh, the keys don't need to be changed. I mean the half-width characters in Chinese translation. [here](https://github.com/wxkj123/MCDoom/blob/70f4d5550089f3b6d7ed9e670967ca5fea85a127/src/main/resources/assets/doom/lang/zh_cn.json#L49)"item.doom.cruciblesword_closed":"裁决剑(失效)" should be "item.doom.cruciblesword_closed":"裁决剑（失效）" "(" → "（" ")" → "）"

请问全角字符是有什么优化之类的，还是说单纯好看，还是为了符合规范呢？

**Comment by Kasualix** [comment]
> > > They can not be changed as they are in-code name of the mod and changing it will remove the old items from saves.
> > 
> > 
> > Oh, the keys don't need to be changed. I mean the half-width characters in Chinese translation. [here](https://github.com/wxkj123/MCDoom/blob/70f4d5550089f3b6d7ed9e670967ca5fea85a127/src/main/resources/assets/doom/lang/zh_cn.json#L49)"item.doom.cruciblesword_closed":"裁决剑(失效)" should be "item.doom.cruciblesword_closed":"裁决剑（失效）" "(" → "（" ")" → "）"
> 
> 请问全角字符是有什么优化之类的，还是说单纯好看，还是为了符合规范呢？

规范。

**Comment by AzureDoom** [comment]
Will be released next update I am currently in the middle of a balancing patch as well.

**Pull request merged**
